// Game balance values and fictional voice lines, not historical measurements or quotations.
export const ADDITIONAL_HEROES = [
  { key: "liubei", name: "유비", title: "인의의 군주", faction: "촉", role: "지휘관", quote: "백성이 머물 곳을 찾는 것이 우리의 첫 승리요.", stats: [80, 68, 72, 88, 99], tile: 0 },
  { key: "zhangfei", name: "장비", title: "장판의 맹호", faction: "촉", role: "무장", quote: "내가 이 길을 지키는 한, 한 발짝도 못 지나간다!", stats: [84, 97, 40, 28, 68], tile: 1 },
  { key: "machao", name: "마초", title: "서량의 금마초", faction: "촉", role: "기장", quote: "서량의 바람보다 빠르게 적진을 가르겠다.", stats: [86, 96, 42, 34, 80], tile: 2 },
  { key: "huangzhong", name: "황충", title: "백발의 명궁", faction: "촉", role: "궁장", quote: "시위를 놓는 순간, 나이는 잊게 될 것이오.", stats: [84, 92, 62, 50, 68], tile: 3 },
  { key: "pangtong", name: "방통", title: "봉추", faction: "촉", role: "책사", quote: "남들이 버린 길에서 승리의 실마리를 찾지요.", stats: [74, 30, 94, 82, 72], tile: 4 },
  { key: "jiangwei", name: "강유", title: "천수의 기린아", faction: "촉", role: "지휘관", quote: "물려받은 뜻은 이 창끝에서 이어집니다.", stats: [88, 88, 88, 72, 78], tile: 5 },
  { key: "weiyan", name: "위연", title: "한중의 수호장", faction: "촉", role: "무장", quote: "험한 길일수록 내가 선봉에 서겠소.", stats: [82, 91, 65, 45, 55], tile: 6 },
  { key: "huangyueying", name: "황월영", title: "기교의 지혜", faction: "촉", role: "책사", quote: "좋은 발명은 백 명의 수고를 덜어 줍니다.", stats: [55, 32, 92, 88, 82], tile: 7 },
  { key: "simayi", name: "사마의", title: "깊이 감춘 계략", faction: "위", role: "책사", quote: "움직일 때를 아는 자가 마지막 수를 둡니다.", stats: [94, 60, 97, 92, 68], tile: 8 },
  { key: "xiahoudun", name: "하후돈", title: "불굴의 맹장", faction: "위", role: "무장", quote: "상처가 깊어질수록 내 결의는 더 단단해진다.", stats: [91, 94, 66, 79, 88], tile: 9 },
  { key: "xiahouyuan", name: "하후연", title: "질풍의 궁장", faction: "위", role: "궁장", quote: "적이 소식을 듣기 전에 우리가 먼저 도착한다.", stats: [88, 91, 59, 52, 72], tile: 10 },
  { key: "zhangliao", name: "장료", title: "합비의 위용", faction: "위", role: "기장", quote: "흩어지지 마라. 우리의 돌격이 전세를 바꾼다.", stats: [95, 92, 78, 60, 80], tile: 11 },
  { key: "xuchu", name: "허저", title: "호치", faction: "위", role: "무장", quote: "주군께 닿으려거든 먼저 나를 넘어라.", stats: [62, 96, 30, 26, 66], tile: 12 },
  { key: "dianwei", name: "전위", title: "쌍극의 호위장", faction: "위", role: "무장", quote: "이 두 자루 극이 버티는 동안 물러서지 않는다.", stats: [66, 95, 31, 27, 70], tile: 13 },
  { key: "xuhuang", name: "서황", title: "침착한 대장", faction: "위", role: "무장", quote: "진형을 지켜라. 빈틈은 반드시 드러난다.", stats: [90, 92, 72, 55, 68], tile: 14 },
  { key: "zhanghe", name: "장합", title: "변통의 명장", faction: "위", role: "기장", quote: "지형이 바뀌면 진법도 새로워져야 한다.", stats: [92, 90, 78, 58, 66], tile: 15 },
  { key: "xunyu", name: "순욱", title: "왕좌의 재사", faction: "위", role: "내정관", quote: "사람을 얻고 살림을 세우면 큰 뜻도 이뤄집니다.", stats: [58, 22, 95, 98, 88], tile: 16 },
  { key: "guojia", name: "곽가", title: "앞을 읽는 눈", faction: "위", role: "책사", quote: "상대의 망설임 속에 이미 답이 있습니다.", stats: [68, 20, 98, 84, 84], tile: 17 },
  { key: "zhenji", name: "견희", title: "고요한 현명함", faction: "위", role: "내정관", quote: "어지러운 마음을 다스리면 길이 보입니다.", stats: [50, 25, 80, 88, 98], tile: 18 },
  { key: "sunquan", name: "손권", title: "강동의 군주", faction: "오", role: "지휘관", quote: "함께 지켜 낸 강동을 함께 키워 나가겠소.", stats: [84, 64, 80, 90, 85], tile: 19 },
  { key: "sunce", name: "손책", title: "소패왕", faction: "오", role: "기장", quote: "망설이지 마라! 우리의 깃발을 강 너머에 세운다.", stats: [92, 93, 68, 66, 94], tile: 20 },
  { key: "zhouyu", name: "주유", title: "강동의 도독", faction: "오", role: "지휘관", quote: "물길과 바람, 사람의 마음까지 살펴야 합니다.", stats: [96, 70, 96, 84, 96], tile: 21 },
  { key: "luxun", name: "육손", title: "차분한 승부사", faction: "오", role: "책사", quote: "기다림도 전술입니다. 불씨가 무르익을 때까지.", stats: [94, 62, 95, 88, 82], tile: 22 },
  { key: "lumeng", name: "여몽", title: "학문을 품은 칼", faction: "오", role: "지휘관", quote: "어제의 나로 오늘의 싸움을 헤아리지 마시오.", stats: [90, 80, 88, 78, 72], tile: 23 },
  { key: "ganning", name: "감녕", title: "금범적", faction: "오", role: "무장", quote: "방울 소리가 들리면 이미 늦은 거다!", stats: [86, 93, 70, 40, 70], tile: 24 },
  { key: "huanggai", name: "황개", title: "불굴의 노장", faction: "오", role: "무장", quote: "몸은 늙었어도 이 결의는 식지 않았소.", stats: [86, 88, 70, 62, 72], tile: 25 },
  { key: "daqiao", name: "대교", title: "강동의 온화함", faction: "오", role: "내정관", quote: "돌아올 이들을 위해 이 터전을 지키겠습니다.", stats: [45, 22, 74, 86, 98], tile: 26 },
  { key: "xiaoqiao", name: "소교", title: "봄바람의 지혜", faction: "오", role: "내정관", quote: "작은 희망도 모이면 모두의 힘이 되지요.", stats: [44, 22, 76, 84, 97], tile: 27 },
  { key: "diaochan", name: "초선", title: "달빛의 계책", faction: "군웅", role: "책사", quote: "칼이 닿지 못하는 곳에도 길은 있습니다.", stats: [50, 25, 86, 82, 100], tile: 28 },
  { key: "yuanshao", name: "원소", title: "하북의 맹주", faction: "군웅", role: "지휘관", quote: "하북의 깃발 아래 천하의 인재를 모으겠소.", stats: [82, 64, 68, 78, 84], tile: 29 },
] as const;
