import {useState} from 'react';
import {ArrowRight,Star,Lock,Wind,Snowflake,Armchair,Lightbulb,Bed,Truck,ArrowsClockwise} from '@phosphor-icons/react';
import {CHAPTERS,LEVELS,type FurnitureKind,type Progress} from './engine';
export function AbilityIcon({kind}:{kind:FurnitureKind}){const Icon={sofa:Armchair,fan:Wind,fridge:Snowflake,vacuum:ArrowsClockwise,lamp:Lightbulb,bed:Bed,cart:Truck}[kind];return <Icon size={22}/>;}
export function ChapterOverview({progress,onSelect}:{progress:Progress;onSelect:(chapter:number)=>void}){return <section className="gm-chapter-preview" aria-label="캠페인 챕터">{CHAPTERS.map((ch,i)=>{const completed=Array.from({length:8},(_,j)=>progress.best[ch.start+j]).filter(Boolean).length;return <button key={ch.name} onClick={()=>onSelect(i)} style={{'--chapter-color':ch.color} as React.CSSProperties}><span className="gm-chapter-no">0{i+1}</span><span><strong>{ch.name}</strong><small>{ch.description}</small></span><span className="gm-chapter-completion">{completed}/8<ArrowRight size={18}/></span></button>;})}</section>;}
export function CampaignMap({progress,initialChapter,onLaunch}:{progress:Progress;initialChapter:number;onLaunch:(index:number)=>void}) {
 const [chapter,setChapter]=useState(initialChapter);
 return <><p className="gm-campaign-summary">{Object.keys(progress.best).length}/24 현장 완료 · {Object.values(progress.best).reduce((n,r)=>n+r.stars,0)}/72 별</p><div className="gm-chapter-tabs" role="tablist" aria-label="챕터 선택">{CHAPTERS.map((ch,i)=><button key={ch.name} role="tab" id={`gm-chapter-${i}`} aria-selected={chapter===i} aria-controls="gm-chapter-panel" onClick={()=>setChapter(i)}>0{i+1}<span>{ch.name}</span></button>)}</div><section id="gm-chapter-panel" role="tabpanel" aria-labelledby={`gm-chapter-${chapter}`}><p className="gm-chapter-description">{CHAPTERS[chapter].description}</p><div className="gm-levels">{LEVELS.slice(CHAPTERS[chapter].start,CHAPTERS[chapter].end).map((l,j)=>{const i=CHAPTERS[chapter].start+j,r=progress.best[i];return <button key={l.name} disabled={i>progress.unlocked} onClick={()=>onLaunch(i)}><span className="gm-level-num">{i>progress.unlocked?<Lock size={20}/>:String(i+1).padStart(2,'0')}</span><span><strong>{l.name}</strong><small>{l.cargo.length}개 짐 · {l.furniture.length}개 가구 · 3별 {l.par} 행동</small></span>{r?<span className="gm-stars" role="img" aria-label={`별 ${r.stars}개`}>{[1,2,3].map(s=><Star key={s} weight={s<=r.stars?'fill':'regular'}/>)}</span>:<span className="gm-level-new">{i>progress.unlocked?'잠김':'출동 가능'}</span>}</button>;})}</div></section></>;
}
