import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowLeft, ArrowRight, ArrowUp, ArrowDown, ArrowUUpLeft, ArrowCounterClockwise, ArrowsClockwise, Ghost, House, Lightbulb, MapTrifold, Pause, Play, Question, SpeakerHigh, SpeakerSlash, Star, X, Check, Package, SignOut } from '@phosphor-icons/react';
import type { GameProps } from '../../platform/types';
import { LEVELS, FURNITURE, chapterOf, SAVE_KEY, act, createState, stars, loadProgress, completeLevel, type State, type Command, type Direction } from './engine';
import { FurnitureArt, GhostArt } from './Room';
import Room from './ThreeRoom';
import { CampaignMap, ChapterOverview, AbilityIcon } from './CampaignUI';
import './ghost-movers.css';

function Stars({count}:{count:number}) {return <span className="gm-stars" role="img" aria-label={`별 ${count}개`}>{[1,2,3].map(i=><Star key={i} weight={i<=count?'fill':'regular'}/>)}</span>;}
function Modal({children,label,onClose}:{children:ReactNode;label:string;onClose:()=>void}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const d=ref.current;if(d&&!d.open)d.showModal();return()=>{d?.close();};},[]);
  return <dialog className="gm-modal" ref={ref} aria-label={label} onCancel={e=>{e.preventDefault();onClose();}}><button className="gm-close gm-icon-button" aria-label="닫기" onClick={onClose}><X size={22}/></button>{children}</dialog>;
}
const keys:Record<string,Direction>={ArrowUp:0,w:0,ArrowRight:1,d:1,ArrowDown:2,s:2,ArrowLeft:3,a:3};
const arrowIcons=[ArrowUp,ArrowRight,ArrowDown,ArrowLeft];
const movementNames=['위로 이동','오른쪽으로 이동','아래로 이동','왼쪽으로 이동'];

export default function GhostMoversApp({onExit}:GameProps) {
  const [run,setRun]=useState<State|null>(null),[paused,setPaused]=useState(false),[panel,setPanel]=useState<'help'|'map'|null>(null),[relaxed,setRelaxed]=useState(false),[sound,setSound]=useState(false),[saveError,setSaveError]=useState(false);
  const [progress,setProgress]=useState(()=>{try{return loadProgress(localStorage.getItem(SAVE_KEY));}catch{return loadProgress(null);}});
  const [mapChapter,setMapChapter]=useState(Math.floor(progress.unlocked/8));
  const preview=useRef({...createState(15),active:'cart'}),root=useRef<HTMLElement>(null),audio=useRef<AudioContext|null>(null),saved=useRef<State|null>(null);
  const state=run??preview.current,l=LEVELS[state.levelIndex],f=state.furniture.find(f=>f.id===state.active),delivered=state.cargo.filter(c=>c.delivered).length;
  const modal=panel!==null||paused||!!run&&run.status!=='playing';
  const command=(c:Command)=>setRun(s=>s?act(s,c):s);
  const launch=(index:number,mode=relaxed)=>{setRun(createState(index,mode));setPanel(null);setPaused(false);root.current?.scrollTo({top:0});};
  const restart=()=>{if(run)launch(run.levelIndex,run.relaxed);};
  const rotate=()=>{if(f)command({type:'face',direction:((f.direction+1)%4) as Direction});};
  const nextFurniture=()=>{if(!run)return;const index=run.furniture.findIndex(f=>f.id===run.active);command({type:'possess',id:run.furniture[(index+1)%run.furniture.length].id});};
  useEffect(()=>{root.current?.scrollTo({top:0});},[run?.levelIndex]);
  useEffect(()=>{
    if(!run||run.status!=='won'||saved.current===run)return;saved.current=run;
    setProgress(p=>{const next=completeLevel(p,run);try{localStorage.setItem(SAVE_KEY,JSON.stringify(next));setSaveError(false);}catch{setSaveError(true);}return next;});
  },[run]);
  useEffect(()=>{
    if(!sound||!run||!run.steps)return;
    try {const ctx=audio.current??new AudioContext();audio.current=ctx;void ctx.resume();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(run.status==='won'?740:run.effect?.kind==='ice'?880:run.effect?.kind==='wind'?400:240,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(run.status==='won'?1100:160,ctx.currentTime+.14);gain.gain.setValueAtTime(.045,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.18);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.2);}catch{/* Silent play works when audio is unavailable. */}
  // Play only when a turn changes, not when a player reads or rotates.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[run?.steps,sound]);
  useEffect(()=>()=>{void audio.current?.close();},[]);
  useEffect(()=>{
    const handler=(e:KeyboardEvent)=>{
      if(e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test((e.target as HTMLElement).tagName))return;
      const k=e.code==='Space'?' ':e.key.length===1?e.key.toLowerCase():e.key;
      if(modal||!run)return;
      if(k==='Escape'){e.preventDefault();setPaused(true);return;}
      if(k in keys){e.preventDefault();if(e.repeat)return;command({type:e.shiftKey?'face':'move',direction:keys[k]});}
      else if(k===' '){e.preventDefault();if(!e.repeat)command({type:'ability'});}
      else if(!e.repeat){if(k==='q'){e.preventDefault();rotate();}else if(k==='e'){e.preventDefault();nextFurniture();}else if(k==='z'){e.preventDefault();command({type:'undo'});}else if(k==='r'){e.preventDefault();restart();}else if(/^[1-9]$/.test(k)){const furniture=run.furniture[Number(k)-1];if(furniture){e.preventDefault();command({type:'possess',id:furniture.id});}}}
    };
    const hidden=()=>{if(document.hidden&&run?.status==='playing')setPaused(true);};
    window.addEventListener('keydown',handler);document.addEventListener('visibilitychange',hidden);
    return()=>{window.removeEventListener('keydown',handler);document.removeEventListener('visibilitychange',hidden);};
  });
  return <main className="gm-app" ref={root}>
    <div className="gm-shell">
      <header className="gm-header"><button className="gm-brand" onClick={()=>{setRun(null);setPaused(false);setPanel(null);}} aria-label="유령 이삿짐센터 시작 화면"><span className="gm-brand-mark"><Ghost weight="fill" size={29}/></span><span>유령 이삿짐센터<small>밤에만 영업합니다</small></span></button><nav aria-label="게임 메뉴"><button className="gm-icon-button" aria-label={sound?'소리 끄기':'소리 켜기'} onClick={()=>setSound(s=>!s)}>{sound?<SpeakerHigh size={22}/>:<SpeakerSlash size={22}/>}</button><button className="gm-icon-button" aria-label="게임 방법" onClick={()=>setPanel('help')}><Question size={23}/></button><button className="gm-exit" aria-label="게임 목록" onClick={onExit}><House size={18}/><span>게임 목록</span></button></nav></header>

      {!run?<>
        <section className="gm-title-screen"><div className="gm-title-copy"><p className="gm-opening"><span/>새벽이 오기 전, 마지막 배송까지</p><h1>유령<br/>이삿짐센터.</h1><p className="gm-intro">몸을 바꾸면, 길이 열린다.<br/>일곱 가구에 빙의하는 한밤의 3D 퍼즐.</p><div className="gm-start-actions"><button className="gm-primary" onClick={()=>launch(progress.unlocked)}><Play weight="fill" size={20}/>{progress.unlocked>0?'야간 근무 이어하기':'첫 의뢰 받기'}</button><button className="gm-text-button" onClick={()=>{setMapChapter(Math.floor(progress.unlocked/8));setPanel('map');}}>의뢰 선택 <ArrowRight size={18}/></button></div><label className="gm-relaxed"><input type="checkbox" checked={relaxed} onChange={e=>setRelaxed(e.target.checked)}/><span>여유 모드 <small>집주인 귀가 걱정 없이</small></span></label><div className="gm-title-note"><Ghost size={18}/><span>무섭지 않아요. 조금 수상할 뿐.</span></div></div><div className="gm-title-room"><div className="gm-scene-label"><span>일곱 가구의 합동 작전</span><strong>가구 연구소 최종 실험</strong></div><Room state={preview.current} preview/><div className="gm-room-caption"><span className="gm-caption-line"/>7가지 능력 · 24개 현장 · 3개 챕터</div></div></section>
        <ChapterOverview progress={progress} onSelect={i=>{setMapChapter(i);setPanel('map');}}/><section className="gm-crew" aria-labelledby="gm-crew-title"><div className="gm-crew-intro"><p>몸 빌려드립니다</p><h2 id="gm-crew-title">일곱 가지 빙의 능력</h2><span>밀고, 당기고, 튕기고, 운반하세요.</span></div>{(Object.keys(FURNITURE) as (keyof typeof FURNITURE)[]).map((kind,i)=><div className="gm-crew-member" key={kind}><svg viewBox="-52 -85 104 114" aria-hidden="true"><FurnitureArt kind={kind}/></svg><div><span className="gm-crew-number">0{i+1}</span><h3>{FURNITURE[kind].name}</h3><p>{FURNITURE[kind].ability}</p></div></div>)}</section>
      </>:<>
        <section className="gm-job-heading"><div><p>야간 의뢰 {String(run.levelIndex+1).padStart(2,'0')} / {LEVELS.length} · {chapterOf(run.levelIndex).name}</p><h1>{l.name}</h1></div><div className="gm-job-tools"><button onClick={()=>{setMapChapter(Math.floor(run.levelIndex/8));setPanel('map');}} className="gm-secondary" aria-label="의뢰 목록"><MapTrifold size={19}/><span>의뢰 목록</span></button><button onClick={()=>setPaused(true)} className="gm-icon-button" aria-label="일시정지"><Pause size={21}/></button></div></section>
        <div className="gm-game-layout"><section className="gm-workspace" aria-label="이사 현장"><div className="gm-board-top"><span><span className="gm-dot"/>{l.client}</span><span><Package size={17}/><strong>{delivered} / {run.cargo.length}</strong> 배송</span></div><div className="gm-room-frame"><Room state={run} onPoint={point=>{if(!modal)command({type:'navigate',point});}} onCargo={id=>{if(!modal)command({type:'target',id});}} onPossess={id=>{if(!modal)command({type:'possess',id});}}/><div className="gm-board-legend"><span><i/>상자 배송</span><span><i/>옷장 배송</span>{l.gates?.length?<span>{run.powered?'전동문 열림':'전동문 닫힘'}</span>:null}</div></div><div className="gm-feedback" role="status" aria-live="polite"><Ghost size={23} weight="fill"/><p>{run.message}</p></div>
          <div className="gm-mobile-possess" aria-label="빙의할 가구" role="group">{run.furniture.map(object=><button key={object.id} aria-pressed={object.id===run.active} disabled={modal} onClick={()=>command({type:'possess',id:object.id})}><svg viewBox="-50 -80 100 110" aria-hidden="true"><FurnitureArt kind={object.kind}/></svg>{FURNITURE[object.kind].name}{object.id===run.active&&<Ghost size={14} weight="fill"/>}</button>)}</div><p className="gm-touch-guide">바닥 누르기: 이동 · 짐 누르기: 다가가서 바라보기<br/>짐 위에 올라가지 않고, 앞에서 능력 버튼 / Space를 눌러요.</p><div className="gm-controls"><div className="gm-dpad" role="group" aria-label="이동 방향">{arrowIcons.map((Icon,d)=><button key={d} className={`gm-direction gm-dir-${d}`} aria-label={movementNames[d]} disabled={!f||modal} onClick={()=>command({type:'move',direction:d as Direction})}><Icon weight="bold" size={23}/></button>)}</div><div className="gm-ability-control"><button className="gm-primary gm-ability" disabled={!f||modal} onClick={()=>command({type:'ability'})}>{<AbilityIcon kind={f?.kind??'sofa'}/>}<span>{f?run.carry?.furnitureId===f.id?'짐 내려놓기':FURNITURE[f.kind].ability:'가구를 눌러 빙의'}<small>Space</small></span></button><button className="gm-rotate" disabled={!f||modal} onClick={rotate}><ArrowsClockwise size={18}/>방향 바꾸기 <kbd>Q</kbd></button></div><div className="gm-utility-controls"><button className="gm-control-tool" disabled={!run.history.length||modal} onClick={()=>command({type:'undo'})}><ArrowUUpLeft size={23}/><span>한 수 되돌리기</span><kbd>Z</kbd></button><button className="gm-control-tool" disabled={modal} onClick={()=>command({type:'hint'})}><Lightbulb size={23}/><span>힌트</span></button><button className="gm-control-tool" disabled={modal} onClick={restart}><ArrowCounterClockwise size={23}/><span>다시 시작</span><kbd>R</kbd></button></div></div><p className="gm-keyboard-note">바닥 클릭 / 방향키 / WASD 이동 · 짐 클릭 후 Space 능력 · E 다음 가구 · Shift + 방향키 제자리 회전</p>
        </section>
        <aside className="gm-docket"><div className="gm-docket-top"><span>야간 배송 의뢰</span><span>No. {String(run.levelIndex+1).padStart(2,'0')}</span></div><h2>{l.client}</h2><p className="gm-client-story">{l.story}</p><div className="gm-delivery-list"><h3>오늘의 이삿짐</h3>{run.cargo.map((c,i)=><div key={c.id} className={c.delivered?'delivered':''}><span className="gm-checkbox">{c.delivered&&<Check size={14} weight="bold"/>}</span><span>{c.kind==='box'?`이삿짐 상자 ${i+1}`:'아주 무거운 옷장'}</span><small>{c.delivered?'배송 완료':run.carry?.cargoId===c.id?'운반 중':'대기 중'}</small></div>)}</div><div className="gm-homecoming"><div><House size={19}/><span>집주인 귀가까지</span><strong>{run.relaxed?'∞':Math.max(0,l.budget-run.steps)}<small>{run.relaxed?'':'행동'}</small></strong></div><div className="gm-owner-track"><span style={{width:`${run.relaxed?0:Math.min(100,run.steps/l.budget*100)}%`}}/></div><p>{run.relaxed?'여유 모드. 마음껏 실험하세요.':'행동할 때만 가까워져요. 천천히 생각하세요.'}</p></div><div className="gm-possess-list"><h3>어디에 빙의할까요? <small>E 전환</small></h3>{run.furniture.map((object,i)=><button key={object.id} aria-pressed={object.id===run.active} disabled={modal} onClick={()=>command({type:'possess',id:object.id})}><svg viewBox="-50 -80 100 110" aria-hidden="true"><FurnitureArt kind={object.kind}/></svg><span>{FURNITURE[object.kind].name}<small>{FURNITURE[object.kind].ability}</small></span>{object.id===run.active?<Ghost size={19} weight="fill"/>:<kbd>{i+1}</kbd>}</button>)}</div><div className="gm-active-note"><strong>{f?`${FURNITURE[f.kind].name} 사용법`:'빙의부터 해 볼까요?'}</strong><p>{f?FURNITURE[f.kind].description:'방 안의 가구나 위 목록을 누르세요. 빙의와 회전은 행동을 쓰지 않아요.'}</p></div><div className="gm-docket-foot"><span>{run.steps} 행동</span><span>3별 목표 {l.par} 행동</span></div></aside></div>
      </>}
      <footer className="gm-footer"><span>유령 이삿짐센터</span><span>몸은 빌려도, 책임은 끝까지.</span><span>달이 뜨면 출근 · 해가 뜨면 퇴근</span></footer>
    </div>

    {panel==='help'&&<Modal label="게임 방법" onClose={()=>setPanel(null)}><div className="gm-modal-ghost"><svg viewBox="-45 -40 90 85"><GhostArt/></svg></div><p className="gm-modal-kicker">신입 유령 업무 안내</p><h2>일곱 가구, 일곱 가지 해결법.</h2><p>가구를 누르면 빙의하고, 빈 바닥을 누르면 이동해요. 짐을 누르면 능력을 쓸 위치로 다가가서 바라봐요. 짐 위에 올라가지 않고 앞에서 Space 또는 화면의 능력 버튼을 누르세요.</p><div className="gm-help-rules">{(Object.keys(FURNITURE) as (keyof typeof FURNITURE)[]).map(kind=><div key={kind}><svg viewBox="-50 -80 100 110" aria-hidden="true"><FurnitureArt kind={kind}/></svg><span><strong>{FURNITURE[kind].name}</strong><p>{FURNITURE[kind].description}</p></span></div>)}</div><p className="gm-help-tip">옷장은 얼음 위에서 밀거나 책상에 실어 옮겨요. 침대는 상자를 두 칸 튕기고, 스탠드는 노란 전동문을 열어요. 실은 짐은 반드시 내려야 배송돼요.</p><dl className="gm-help-keys"><div><dt>방향키 / WASD</dt><dd>이동</dd></div><div><dt>Space</dt><dd>가구 능력</dd></div><div><dt>Q / Shift + 방향키</dt><dd>제자리 회전</dd></div><div><dt>E / 1–9</dt><dd>빙의할 가구 전환</dd></div><div><dt>Z / R / Esc</dt><dd>되돌리기 / 재시작 / 쉬기</dd></div></dl><button className="gm-primary" onClick={()=>setPanel(null)}>업무 이해 완료 <Check size={20}/></button></Modal>}
    {panel==='map'&&<Modal label="이사 의뢰 목록" onClose={()=>setPanel(null)}><p className="gm-modal-kicker">24개 현장 · 3개 챕터</p><h2>오늘 밤은 어느 동네로?</h2><CampaignMap progress={progress} initialChapter={mapChapter} onLaunch={index=>launch(index)}/><label className="gm-relaxed gm-dark-label"><input type="checkbox" checked={relaxed} onChange={e=>setRelaxed(e.target.checked)}/><span>여유 모드 <small>귀가 제한 없이 플레이</small></span></label></Modal>}
    {!panel&&paused&&<Modal label="일시정지" onClose={()=>setPaused(false)}><div className="gm-modal-ghost"><svg viewBox="-45 -40 90 85"><GhostArt/></svg></div><p className="gm-modal-kicker">잠깐 쉬어 갑니다</p><h2>유령도 휴식은 필요해요.</h2><p>이삿짐은 그대로 있어요. 준비되면 돌아오세요.</p><div className="gm-modal-actions"><button className="gm-primary" onClick={()=>setPaused(false)}><Play weight="fill"/>계속 일하기</button><button className="gm-secondary" onClick={restart}><ArrowCounterClockwise/>다시 시작</button><button className="gm-text-button" onClick={()=>{setRun(null);setPaused(false);}}><SignOut/>시작 화면</button></div></Modal>}
    {!panel&&!paused&&run?.status==='won'&&<Modal label="이사 완료" onClose={()=>setRun(null)}><div className="gm-complete-stamp"><Check size={38} weight="bold"/><span>이사 완료</span></div><p className="gm-modal-kicker">{l.client}의 감사 인사</p><h2>{run.levelIndex===LEVELS.length-1?'24개 현장, 모두 완료!':'짐은 도착, 유령은 퇴근!'}</h2><Stars count={stars(run)}/><p>{run.levelIndex===LEVELS.length-1?'세 챕터와 24개 현장을 마쳤어요. 이제 당신은 베테랑 야간 이사 전문가!':'“분명 가구가 혼자 움직인 것 같은데… 아무튼 정말 감사합니다!”'}</p><div className="gm-result-stats"><span><strong>{run.steps}</strong>사용한 행동</span><span><strong>{run.undos}</strong>되돌린 횟수</span><span><strong>{l.par}</strong>3별 목표</span></div>{saveError&&<p role="alert">기록을 저장하지 못했어요. 지금 열린 게임에서는 계속할 수 있어요.</p>}<div className="gm-modal-actions">{run.levelIndex<LEVELS.length-1?<button className="gm-primary" onClick={()=>launch(run.levelIndex+1,run.relaxed)}>다음 의뢰 받기 <ArrowRight size={20}/></button>:<button className="gm-primary" onClick={()=>{setRun(null);}}>퇴근하기 <Ghost size={20}/></button>}<button className="gm-secondary" onClick={restart}>별 세 개 다시 도전</button></div></Modal>}
    {!panel&&!paused&&run?.status==='lost'&&<Modal label="집주인 귀가" onClose={()=>command({type:'undo'})}><div className="gm-modal-ghost"><svg viewBox="-45 -40 90 85"><GhostArt smile={false}/></svg></div><p className="gm-modal-kicker">열쇠 돌아가는 소리가 들려요</p><h2>앗, 집주인이 돌아왔어요!</h2><p>한 수 되돌려 길을 바꾸거나, 귀가 제한 없는 여유 모드로 연습해 보세요.</p><div className="gm-modal-actions"><button className="gm-primary" onClick={()=>command({type:'undo'})}><ArrowUUpLeft/>한 수 되돌리기</button><button className="gm-secondary" onClick={()=>launch(run.levelIndex,true)}>여유 모드로 다시 하기</button><button className="gm-text-button" onClick={restart}>같은 의뢰 다시 도전</button></div></Modal>}
  </main>;
}
