import { lazy } from 'react';
const HachupingSliderApp = lazy(() => import('../games/hachuping-slither/HachupingSliderApp'));
const HachupingJumpApp = lazy(() => import('../games/hachuping-jump/HachupingJumpApp'));
const RuneRangerApp = lazy(() => import('../games/hachuping-dodge/survivor/SurvivorApp'));
const HachupingBalloonApp = lazy(() => import('../games/hachuping-balloon/HachupingBalloonApp'));
const HachupingMemoryApp = lazy(() => import('../games/hachuping-memory/HachupingMemoryApp'));
const HachupingColorMatchApp = lazy(() => import('../games/hachuping-color-match/HachupingColorMatchApp'));
const GhostMoversApp = lazy(() => import('../games/ghost-movers/GhostMoversApp'));
const FantasyTacticsApp = lazy(() => import('../games/fantasy-tactics/FantasyTacticsApp'));
const EchoMazeApp = lazy(() => import('../games/echo-maze/EchoMazeApp'));
const TenSecondsApp = lazy(() => import('../games/ten-seconds/TenSecondsApp'));
const HachupingWhackAMoleApp = lazy(() => import('../games/hachuping-whack-a-mole/HachupingWhackAMoleApp'));
const ThreeKingdomsApp = lazy(() => import('../games/three-kingdoms/ThreeKingdomsApp'));
const ThreeKingdomsCardApp = lazy(() => import('../games/three-kingdoms-card/ThreeKingdomsCardApp'));
import type { GameDefinition } from "./types";

/** Every playable game on the platform. Add a new entry here to list a new game on the hub. */
export const GAMES: GameDefinition[] = [
  {
    id: 'ghost-movers',
    title: '유령 이삿짐센터',
    description: '일곱 가구에 빙의하는 3D 이사 퍼즐 · 3개 챕터와 24개 야간 배송 현장',
    thumbnail: '/art/hub/ghost-movers.jpg',
    cover: '/art/hub/ghost-movers-large.jpg',
    previewThumbnail: '/art/hub/ghost-movers-small.jpg',
    spotlightText: "일곱 가구의 능력을 연결해, 24개의 야간 이사 의뢰를 해결하세요.",
    accentColor: '#a8d7c0',
    genres: ['전략', '캐주얼'],
    tags: ['3D', '퍼즐', '빙의', '유령', '이사'],
    featuredText: '몸을 바꾸면, 길이 열립니다. 밀고 당기고 튕기고 운반하는 일곱 가구의 능력을 연결해 24개 이사 현장을 해결하세요.',
    Component: GhostMoversApp,
  },
  {
    id: 'ten-seconds',
    title: '텐 세컨즈 · 시간의 잔상',
    description: '10초 전의 나와 협동하는 3D 시간 퍼즐 · 과거의 발걸음으로 다음 순간을 열어 보세요',
    thumbnail: '/art/hub/ten-seconds.jpg',
    cover: '/art/hub/ten-seconds-large.jpg',
    previewThumbnail: '/art/hub/ten-seconds-small.jpg',
    spotlightText: "10초 전의 나와 함께 발판과 문을 연결하는 시간 퍼즐.",
    accentColor: '#9acbbb',
    genres: ['전략', '캐주얼'],
    tags: ['3D', '퍼즐', '시간 루프', '협동', '잔상'],
    featuredText: '혼자서는 열 수 없는 문. 10초의 기억을 남기고 과거의 나와 함께 아홉 개의 시간 연구실을 탈출하세요. 짧게 켜지는 발판과 시간 문을 연결하는 고급 실험에 도전하세요.',
    Component: TenSecondsApp,
  },
  {
    id: 'fantasy-tactics',
    title: '별빛 원정대',
    description: '네 동료와 떠나는 6개 챕터의 전술 RPG · 전직과 지형 전술로 바다 건너 별빛까지',
    thumbnail: '/art/hub/fantasy-tactics.jpg',
    cover: '/art/hub/fantasy-tactics-large.jpg',
    previewThumbnail: '/art/hub/fantasy-tactics-small.jpg',
    spotlightText: "네 동료와 숲에서 바다 너머까지. 전직과 지형을 활용하는 전술 RPG.",
    accentColor: '#416d79',
    genres: ['전략'],
    tags: ['턴제', 'RPG', '판타지', '스토리', '전술'],
    featuredText: '등대에 돌아온 빛이 바다 건너에서 응답합니다. 숲과 언덕을 지나 항구·유령선·별이 떨어진 섬으로 원정을 이어 가세요.',
    Component: FantasyTacticsApp,
  },
  {
    id: "echo-maze",
    title: "메아리 미로",
    description: "내 사진으로 떠나는 3D 미로 탐험 · 기억 닻과 시간 조각을 이용해 탈출하세요",
    thumbnail: '/art/hub/echo-maze.jpg',
    cover: '/art/hub/echo-maze-large.jpg',
    previewThumbnail: '/art/hub/echo-maze-small.jpg',
    spotlightText: "기억 닻과 시간 조각으로 길을 찾아, 미로의 출구에 도착하세요.",
    accentColor: "#78b79b",
    genres: ["캐주얼"],
    tags: ["미로", "3D", "사진 캐릭터", "시간 제한"],
    Component: EchoMazeApp,
  },
  {
    id: "three-kingdoms-card",
    title: "삼국 영지",
    description: "장수를 모집하고 부대를 편성해 나만의 영지를 키우는 삼국지 카드 전략",
    thumbnail: '/art/hub/three-kingdoms-card.jpg',
    cover: '/art/hub/three-kingdoms-card-large.jpg',
    previewThumbnail: '/art/hub/three-kingdoms-card-small.jpg',
    spotlightText: "장수를 모으고 부대를 편성해, 당신의 영지를 키우세요.",
    accentColor: "#d4b678",
    genres: ["전략"],
    tags: ["삼국지", "카드", "수집", "영지", "부대 편성"],
    featuredText: "72명의 장수를 모으고, 당신만의 영지에서 새로운 천하를 시작하세요.",
    Component: ThreeKingdomsCardApp,
  },
  {
    id: "three-kingdoms",
    title: "삼국지 패업 PK",
    description: "3D 중원 전장 · 장수별 모델과 PK 편집 · 육각 턴제 전략",
    thumbnail: '/art/hub/three-kingdoms.jpg',
    cover: '/art/hub/three-kingdoms-large.jpg',
    previewThumbnail: '/art/hub/three-kingdoms-small.jpg',
    spotlightText: "육각 전장에서 장수를 지휘하고, 중원의 도시를 차지하세요.",
    accentColor: "#7a2020",
    genres: ["전략"],
    tags: ["삼국지", "3D", "턴제", "PK", "전쟁"],
    Component: ThreeKingdomsApp,
  },
  {
    id: "hachuping-slither",
    title: "슬리더",
    description: "별을 먹고 커지는 지렁이 게임",
    thumbnail: '/art/hub/hachuping-slither.jpg',
    cover: '/art/hub/hachuping-slither-large.jpg',
    previewThumbnail: '/art/hub/hachuping-slither-small.jpg',
    spotlightText: "별을 먹고 몸집을 키워, 지렁이들의 경쟁에서 살아남으세요.",
    accentColor: "#72bd85",
    genres: ["액션", "캐주얼"],
    tags: ["성장", "지렁이", "아케이드", "점수"],
    Component: HachupingSliderApp,
  },
  {
    id: "hachuping-dodge",
    title: "룬 레인저",
    description: "자동 사격과 레벨업으로 미니언 군단을 돌파하는 생존 액션 RPG",
    thumbnail: '/art/hub/hachuping-dodge.jpg',
    cover: '/art/hub/hachuping-dodge-large.jpg',
    previewThumbnail: '/art/hub/hachuping-dodge-small.jpg',
    spotlightText: "룬의 힘으로 미니언 군단을 돌파하는 생존 액션.",
    accentColor: "#77cba3",
    genres: ["액션"],
    tags: ["생존", "RPG", "자동 전투", "레벨업"],
    Component: RuneRangerApp,
  },
  {
    id: "hachuping-jump",
    title: "점프",
    description: "장애물 사이를 뚫고 날아가는 점프 게임",
    thumbnail: '/art/hub/hachuping-jump.jpg',
    cover: '/art/hub/hachuping-jump-large.jpg',
    previewThumbnail: '/art/hub/hachuping-jump-small.jpg',
    spotlightText: "떠 있는 섬과 장애물 사이로 날아가는 점프 챌린지.",
    accentColor: "#4fd8ff",
    genres: ["액션", "캐주얼"],
    tags: ["점프", "비행", "장애물", "아케이드"],
    Component: HachupingJumpApp,
  },
  {
    id: "hachuping-memory",
    title: "동물 친구 기억력",
    description: "패턴을 보고 따라하는 7세 두뇌 발달 게임",
    thumbnail: '/art/hub/hachuping-memory.jpg',
    cover: '/art/hub/hachuping-memory-large.jpg',
    previewThumbnail: '/art/hub/hachuping-memory-small.jpg',
    spotlightText: "동물 친구들의 패턴을 기억하고 따라 해 보세요.",
    accentColor: "#ff6fa5",
    genres: ["키즈", "캐주얼"],
    tags: ["기억력", "동물", "두뇌", "패턴"],
    releaseStatus: "coming-soon",
    disabled: true,
    Component: HachupingMemoryApp,
  },
  {
    id: "hachuping-whack-a-mole",
    title: "두더지 잡기",
    description: "톡! 톡! 3D 두더지와 즐기는 30초 순발력 챌린지",
    thumbnail: '/art/hub/hachuping-whack-a-mole.jpg',
    cover: '/art/hub/hachuping-whack-a-mole-large.jpg',
    previewThumbnail: '/art/hub/hachuping-whack-a-mole-small.jpg',
    spotlightText: "30초 동안 두더지를 톡톡. 빠르고 정확한 터치에 도전하세요.",
    accentColor: "#ff9020",
    genres: ["액션", "캐주얼", "키즈"],
    tags: ["두더지", "반응 속도", "3D", "30초"],
    Component: HachupingWhackAMoleApp,
  },
  {
    id: "hachuping-color-match",
    title: "색깔 맞추기",
    description: "화면에 뜬 색과 같은 색을 빠르게 찾는 반응속도 게임",
    thumbnail: '/art/hub/hachuping-color-match.jpg',
    cover: '/art/hub/hachuping-color-match-large.jpg',
    previewThumbnail: '/art/hub/hachuping-color-match-small.jpg',
    spotlightText: "화면과 같은 색을 빠르게 찾는 반응 속도 게임.",
    accentColor: "#22c55e",
    genres: ["키즈", "캐주얼"],
    tags: ["색깔", "반응 속도", "교육"],
    releaseStatus: "coming-soon",
    disabled: true,
    Component: HachupingColorMatchApp,
  },
  {
    id: "hachuping-balloon",
    title: "풍선 터뜨리기",
    description: "반짝이는 풍선과 별, 하트를 톡! 60초 동안 즐기는 하늘 위 풍선 축제.",
    thumbnail: '/art/hub/hachuping-balloon.jpg',
    cover: '/art/hub/hachuping-balloon-large.jpg',
    previewThumbnail: '/art/hub/hachuping-balloon-small.jpg',
    spotlightText: "풍선도 별도 하트도, 톡! 하늘 가득 색종이가 팡!",
    accentColor: "#ffb020",
    genres: ["키즈", "캐주얼"],
    tags: ["풍선", "터치", "유아", "반응 속도"],
    Component: HachupingBalloonApp,
  },
];

export function getGameById(id: string): GameDefinition | undefined {
  return GAMES.find((g) => g.id === id && !g.disabled);
}
